from .maestros import cliente_bp
from .maestros import familia_bp
from .maestros import producto_bp
from .maestros import tecnico_bp
from .maestros import vendedor_bp
from .maestros import visita_bp
from .maestros import usuarios_bp
from .maestros import bp_visitas
from .maestros import proxy_bp
