from .maestros import ClienteModel
from .maestros import VendedorModel
from .maestros import  ProductoModel
from .transacciones import  cabRegITModel
from .transacciones import  detModel
from .maestros import  TecnicosModel
from .maestros import  FamiliaModel
from .maestros import  TipoVisitaModel
from .maestros import Usuario
from .maestros import EmpleadoModel